### ISSUE TITLE
Shader should use RAII to deallocate memory

### ISSUE THREAD

**Issue by wmcnamara** [Sammie156/HyperVision#11]
Currently the shader class deallocates memory with the Delete() function. This should be in the classes destructor, so that a user does not have to worry about forgetting to call Delete

There should also be move and copy constructors defined for this class to follow the [rule of 5](https://en.cppreference.com/w/cpp/language/rule_of_three)

**Comment by Sammie156** [comment]
Thanks for pointing that out. I'll get to working on this as soon as possible.
