### ISSUE TITLE
Include and linker directories are not in the download vcxproj file

### ISSUE THREAD

**Issue by wmcnamara** [Sammie156/HyperVision#4]
Currently, when the project is downloaded, the include and linker directories are not committed to the project, so I have to set up the directories by myself which is extremely cumbersome, and it has to be done every time I merge upstream changes for my own fork.

<img src="https://i.imgur.com/Zy6dg9W.png" width="600" height="400">

This issue suggests that you use relative directories for the include and linker dependency dirs, and commit those

**Comment by Sammie156** [comment]
Hello @wmcnamara. Thanks for opening this issue. As of commit [Update Project and OpenGL version](https://github.com/Sammie156/HyperVision/commit/385931f26618b9bf7e670d105325f59d7a8c5c83), the issue should be fixed. Can you please check this and get back?

**Comment by wmcnamara** [comment]
Yes, it works for me now. Thanks!
